export const products = [
  {
    id: "tee-oversized-black",
    name: "Oversized Tee",
    category: "T-Shirts",
    price: 899,
    rating: 4.6,
    sizes: ["S", "M", "L", "XL"],
    color: "Black",
    blurb: "Soft cotton, relaxed drape, everyday staple.",
  },
  {
    id: "tee-ribbed-white",
    name: "Ribbed Slim Tee",
    category: "T-Shirts",
    price: 799,
    rating: 4.4,
    sizes: ["XS", "S", "M", "L"],
    color: "White",
    blurb: "Clean fit with rib texture — easy to layer.",
  },
  {
    id: "shirt-oxford-blue",
    name: "Oxford Shirt",
    category: "Shirts",
    price: 1599,
    rating: 4.7,
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    blurb: "Crisp collar, breathable weave, office-to-weekend.",
  },
  {
    id: "shirt-linen-sand",
    name: "Linen Shirt",
    category: "Shirts",
    price: 1799,
    rating: 4.5,
    sizes: ["S", "M", "L", "XL"],
    color: "Sand",
    blurb: "Lightweight linen — made for warm days.",
  },
  {
    id: "jeans-straight-indigo",
    name: "Straight Jeans",
    category: "Jeans",
    price: 2199,
    rating: 4.6,
    sizes: ["S", "M", "L", "XL"],
    color: "Indigo",
    blurb: "Classic straight leg with premium stretch denim.",
  },
  {
    id: "jeans-relaxed-washed",
    name: "Relaxed Jeans",
    category: "Jeans",
    price: 2399,
    rating: 4.3,
    sizes: ["S", "M", "L", "XL"],
    color: "Washed Blue",
    blurb: "Roomy through the thigh for all-day comfort.",
  },
  {
    id: "hoodie-fleece-graphite",
    name: "Fleece Hoodie",
    category: "Hoodies",
    price: 1999,
    rating: 4.8,
    sizes: ["S", "M", "L", "XL"],
    color: "Graphite",
    blurb: "Thick fleece, warm hood, minimal branding.",
  },
  {
    id: "hoodie-zip-olive",
    name: "Zip Hoodie",
    category: "Hoodies",
    price: 2099,
    rating: 4.4,
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "Olive",
    blurb: "Easy zip-up layer with clean seams.",
  },
  {
    id: "jacket-bomber-forest",
    name: "Bomber Jacket",
    category: "Jackets",
    price: 3299,
    rating: 4.7,
    sizes: ["S", "M", "L", "XL"],
    color: "Forest",
    blurb: "Structured bomber with a smooth matte finish.",
  },
  {
    id: "jacket-denim-mid",
    name: "Denim Jacket",
    category: "Jackets",
    price: 2999,
    rating: 4.5,
    sizes: ["S", "M", "L", "XL"],
    color: "Mid Blue",
    blurb: "Iconic denim layer — works with everything.",
  },
  {
    id: "dress-midi-berry",
    name: "Midi Dress",
    category: "Dresses",
    price: 2799,
    rating: 4.6,
    sizes: ["XS", "S", "M", "L"],
    color: "Berry",
    blurb: "Flowy silhouette with a flattering waist tie.",
  },
  {
    id: "dress-shirt-black",
    name: "Shirt Dress",
    category: "Dresses",
    price: 2599,
    rating: 4.3,
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "Black",
    blurb: "Button-down dress with crisp structure.",
  },
];

export const categories = Array.from(new Set(products.map((p) => p.category))).sort();
